################################################################################
# Environment script generated by ilcsoft-install on Wed Jul 26 19:09:55 2017
# for the installation located at [ /cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-04 ]
################################################################################

SET( ILC_HOME "/cvmfs/ilc.desy.de/sw/x86_64_gcc49_sl6/v01-19-04" CACHE PATH "Path to ILC Software" FORCE)
MARK_AS_ADVANCED( ILC_HOME )

SET( CMAKE_PREFIX_PATH 
	${ILC_HOME}/lccd/v01-04;
	${ILC_HOME}/Marlin/v01-12;
	${ILC_HOME}/MarlinDD4hep/v00-05;
	${ILC_HOME}/DDMarlinPandora/v00-07;
	${ILC_HOME}/MarlinUtil/v01-14;
	${ILC_HOME}/MarlinReco/v01-19-01;
	${ILC_HOME}/PandoraAnalysis/v01-02-01;
	${ILC_HOME}/PandoraPFANew/v03-01-02;
	${ILC_HOME}/LCFIVertex/v00-07-04;
	${ILC_HOME}/CEDViewer/v01-14-01;
	${ILC_HOME}/Overlay/v00-18;
	${ILC_HOME}/MarlinFastJet/v00-05;
	${ILC_HOME}/LCTuple/v01-08;
	${ILC_HOME}/MarlinKinfit/v00-05;
	${ILC_HOME}/MarlinTrk/v02-04;
	${ILC_HOME}/KiTrack/v01-08;
	${ILC_HOME}/KiTrackMarlin/v01-11;
	${ILC_HOME}/MarlinTrkProcessors/v02-08-01;
	${ILC_HOME}/MarlinKinfitProcessors/v00-03;
	${ILC_HOME}/ILDPerformance/v01-03;
	${ILC_HOME}/Clupatra/v01-01;
	${ILC_HOME}/Physsim/v00-04;
	${ILC_HOME}/LCFIPlus/v00-06-06;
	${ILC_HOME}/ForwardTracking/v01-12;
	${ILC_HOME}/ConformalTracking/v01-03;
	${ILC_HOME}/LICH/v00-01;
	${ILC_HOME}/pathfinder/v00-06-01;
	${ILC_HOME}/MarlinTPC/v01-03;
	${ILC_HOME}/bbq/v00-01-03;
	${ILC_HOME}/Garlic/v3.0.4;
	${ILC_HOME}/RAIDA/v01-08;
	${ILC_HOME}/KalTest/v02-03;
	${ILC_HOME}/KalDet/v01-14;
	${ILC_HOME}/GBL/V02-01-01;
	${ILC_HOME}/xercesc/3.1.4;
	${ILC_HOME}/DD4hep/v01-01-01;
	${ILC_HOME}/lcgeo/v00-13-04;
	${ILC_HOME}/aidaTT/v00-07;
	${ILC_HOME}/DDKalTest/v01-03-01;
	${ILC_HOME}/DD4hepExamples/v01-01-01;
	${ILC_HOME}/CED/v01-09-02;
	${ILC_HOME}/lcio/v02-09;
	${ILC_HOME}/gear/v01-07;
	${ILC_HOME}/FastJet/3.2.0;
	${ILC_HOME}/root/6.08.02;
	${ILC_HOME}/CLHEP/2.3.1.1;
	${ILC_HOME}/gsl/2.1;
	${ILC_HOME}/QT/4.7.4;
	${ILC_HOME}/geant4/10.02.p02;
	${ILC_HOME}/CondDBMySQL/CondDBMySQL_ILC-0-9-6;
	${ILC_HOME}/mysql/5.0.45;
	${ILC_HOME}/ilcutil/v01-03;
	/cvmfs/ilc.desy.de/sw/boost/1.58.0;
	/cvmfs/ilc.desy.de/sw/Eigen/3.2.9;
CACHE PATH "CMAKE_PREFIX_PATH" FORCE )


option(USE_CXX11 "Use cxx11" True)
option(Boost_NO_BOOST_CMAKE "dont use cmake find module for boost" ON)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O2 -g" CACHE STRING "" FORCE )
